### PR TITLE
test binary in empty folder

### PR DESCRIPTION
**Pull request by williscool**
# test binary in empty folder 

## Description

Use docker container to tset binary inside of empty folder (so we can catch bugs introduced by files neded from the source that won;t be ther for curl installs)

## Issues:
Refs: #398 

## How has this been tested:
 - [x] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [x] Tasks in issue are checked off

### CODE REVIEW

**Comment by williscool** [comment]
Example of a good break

at commit https://github.com/cncf/cnf-conformance/pull/418/commits/c4a6f1faa6360701fae133aafee702498963b82d

the test runss

```
./cnf-conformance sample_coredns_setup
```

and errors out with

```
No cnf_conformance.yml found in sample-cnfs/sample-coredns-cnf!
```

https://travis-ci.org/github/cncf/cnf-conformance/builds/732035537

because that command relies on the source code dir `sample-cnfs`


that is an internal command only used for spec tests so its fine.

now I plan to update to 

```
wget https://raw.githubusercontent.com/cncf/cnf-conformance/master/example-cnfs/coredns/cnf-conformance.yml
cnf-conformance all cnf-config=./cnf-conformance.yml
```

i.e. from

https://github.com/cncf/cnf-conformance/issues/369#issuecomment-680961684

which should work without needed the rest of the source.

this tell us early if we inadvertnely added a dependency for the static binary to any configuration from the source files

**Comment by williscool** [comment]
still workin on it https://api.travis-ci.org/v3/job/732041812/log.txt
```

Connection to [secure] closed.

E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: Error while changing directory: 'cnfs': No such file or directory
E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../usr/share/crystal/src/crystal/system/unix/dir.cr:47:13 in '->'
E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../usr/share/crystal/src/primitives.cr:255:3 in 'task_runner'
E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../workspace/src/tasks/configuration_lifecycle.cr:16:3 in '->'
E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../workspace/lib/sam/src/sam.cr:43:5 in '__crystal_main'
E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

**Comment by williscool** [comment]
> still workin on it https://api.travis-ci.org/v3/job/732041812/log.txt
> 
> ```
> 
> Connection to [secure] closed.
> 
> E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: Error while changing directory: 'cnfs': No such file or directory
> E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../usr/share/crystal/src/crystal/system/unix/dir.cr:47:13 in '->'
> E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../usr/share/crystal/src/primitives.cr:255:3 in 'task_runner'
> E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../workspace/src/tasks/configuration_lifecycle.cr:16:3 in '->'
> E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../workspace/lib/sam/src/sam.cr:43:5 in '__crystal_main'
> E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: ../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
> E, [2020-10-01 19:02:49 UTC #1] ERROR -- cnf-conformance: src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
> ```

turns out this was a bug #426

**Comment by williscool** [comment]
this (hopefully) https://travis-ci.org/github/cncf/cnf-conformance/builds/733199171

is an example of a good build. no issue from missing yaml config files should pop up

**Comment by williscool** [comment]
Closed to reopened to get rebuild

https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit/17624403#17624403

**Review by wavell — APPROVED** [review]

**Review by taylor — APPROVED** [review]
lgtm

**Pull request merged**
