### PR TITLE
#336 moved emoji to variable

### PR DESCRIPTION
**Pull request by sakshamgurbhele**
# hardcoded emoji update

## Description
Replaced hardcoded emojis with variables
## Issues:
Refs: #336 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Review by taylor — APPROVED** [review]
lgtm

**Comment by taylor** [comment]
@williscool release manager is failing. everything else looks good

**Comment by taylor** [comment]
@wavell @denverwilliams

**Review by williscool — APPROVED** [review]
lgtm too.

will rebase and see if that fixes

**Pull request merged**
