### PR TITLE
Docs/private docker registry #577 #606

### PR DESCRIPTION
**Pull request by agentpoyo**
## Description
Documentation updates to add Private Docker Registry

## Issues:
Refs: #577 #606

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Comment by agentpoyo** [comment]
@taylor adding you to review.

**Review by taylor — CHANGES_REQUESTED** [review]
Instead of having QUICK-INSTALL.md lets add the commands to README-testsuite.md (which will eventually become README.md after the repo is split up).   Add the quick steps here https://github.com/cncf/cnf-conformance/blob/master/README-testsuite.md#installation

Example:

## Installation

To get the CNF Test Suite up and running, see the [Installation Guide](INSTALL.md). 

### Quick install steps
Prereqs: kubernetes cluster, wget, curl, helm 3.1.1 or greater on your system already.

1. Install the latest test suite binary:  `source <(curl https://raw.githubusercontent.com/cncf/cnf-conformance/master/curl_install.sh)`
2. Run `setup` to prepare the cnf-conformance suite: `cnf-conformance setup`
3. Pull down an example CNF configuration to try: `wget -O cnf-conformance.yml https://raw.githubusercontent.com/cncf/cnf-conformance/master/example-cnfs/coredns/cnf-conformance.yml`
4. Initialize the test suite for using the CNF: `cnf-conformance cnf_setup cnf-config=./cnf-conformance.yml`
5. Run all of application/workload tests: `cnf-conformance workload`

**Review by taylor — COMMENTED** [review]
small changes

**Review by taylor — APPROVED** [review]
lgtm

**Pull request merged**
