### PR TITLE
Logging Refactor

### PR DESCRIPTION
**Pull request by williscool**
# CNF Conformance PR Template

## Description
(name of issue/change)

## Issues:
Refs: #280 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Comment by williscool** [comment]
So I've noticed that not all `puts` all created equal.

Some will likely stay i.e. the final test success or failure

```
✔️  PASSED: hostPath volumes not found 🖥️  💾
Statelessness final score: 9 of 5

```

**Comment by williscool** [comment]
re @taylor 's feedback we will move all of the `puts` with a `colorize` call that is the pass/fail messages out to a function

**Comment by williscool** [comment]
also I'm adding a crap ton of `LOGGING.debug` calls.

Will need everyone's help with the code they know best as to which ones should actually be `LOGGING.info`

**Comment by wavell** [comment]
You'll want to pull in master so that your chaos mesh tests pass.  We had to tag a specific version of chaos mesh

**Comment by williscool** [comment]
think this pr is large enough and since @wavell already approved will merge this and continue refactor in another branch

**Pull request merged**
